# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUBpHuaU1WwSe_1S34exSf5Uqk-Zo-7y
"""

import streamlit as st
from itertools import product

st.set_page_config(page_title="Virtual Lab Kombinasi", layout="wide")
st.title("📚 Virtual Lab: Kombinasi Outfit")

st.info("🧩 Soal: Siswa memiliki 4 kaos dan 3 celana. Berapa banyak cara memilih satu kaos dan satu celana?")

kaos = {
    "Kaos 1": "...URL gambar kaos1...",
    "Kaos 2": "...URL kaos2...",
    "Kaos 3": "...URL kaos3...",
    "Kaos 4": "...URL kaos4..."
}
celana = {
    "Celana 1": "...URL celana1...",
    "Celana 2": "...URL celana2...",
    "Celana 3": "...URL celana3..."
}

selected_kaos = st.multiselect("Pilih Kaos", list(kaos.keys()), default=list(kaos.keys()))
selected_celana = st.multiselect("Pilih Celana", list(celana.keys()), default=list(celana.keys()))

st.markdown("**Kaos Terpilih:**")
cols = st.columns(len(selected_kaos))
for i,k in enumerate(selected_kaos):
    with cols[i]:
        st.image(kaos[k], width=80, caption=k)

st.markdown("**Celana Terpilih:**")
cols = st.columns(len(selected_celana))
for i,c in enumerate(selected_celana):
    with cols[i]:
        st.image(celana[c], width=80, caption=c)

if st.button("Tampilkan Kombinasi"):
    if not selected_kaos or not selected_celana:
        st.warning("Pilih minimal 1 kaos dan 1 celana")
    else:
        combos = list(product(selected_kaos, selected_celana))
        st.success(f"Jumlah kombinasi: {len(combos)} (rumus: {len(selected_kaos)} × {len(selected_celana)})")
        for k,c in combos:
            col1, col2, col3 = st.columns([1,1,2])
            with col1:
                st.image(kaos[k], width=80)
            with col2:
                st.image(celana[c], width=80)
            with col3:
                st.write(f"**{k} + {c}**")
            st.markdown("---")