# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBINOhQageSgGqevCG-gyDgn9GkkfN6g
"""

import streamlit as st
from PIL import Image
import itertools

st.set_page_config(page_title="Virtual Lab Kombinasi Outfit", layout="wide")
st.title("👕👖 Virtual Lab Kombinasi Outfit")

st.markdown("""
#### Soal:
Seorang siswa memiliki **4 kaos** dan **3 celana**.
Berapa banyak cara memilih **2 pakaian berbeda (1 kaos dan 1 celana)** untuk kombinasi outfit?
""")

kaos_list = ["Kaos 1", "Kaos 2", "Kaos 3", "Kaos 4"]
celana_list = ["Celana 1", "Celana 2", "Celana 3"]

kaos_imgs = {
    "Kaos 1": "👕 Kaos 1",
    "Kaos 2": "🧥 Kaos 2",
    "Kaos 3": "👚 Kaos 3",
    "Kaos 4": "🎽 Kaos 4"
}
celana_imgs = {
    "Celana 1": "👖 Celana 1",
    "Celana 2": "🩳 Celana 2",
    "Celana 3": "👘 Celana 3"
}

st.markdown("### 1. Pilih Kaos dan Celana")
col1, col2 = st.columns(2)
with col1:
    selected_kaos = st.multiselect("Pilih Kaos:", kaos_list, default=kaos_list)
    st.write("Kaos Terpilih:")
    for k in selected_kaos:
        st.write(kaos_imgs[k])

with col2:
    selected_celana = st.multiselect("Pilih Celana:", celana_list, default=celana_list)
    st.write("Celana Terpilih:")
    for c in selected_celana:
        st.write(celana_imgs[c])

st.markdown("### 2. Kombinasi yang Dapat Dibentuk")
kombinasi = list(itertools.product(selected_kaos, selected_celana))
st.success(f"Jumlah kombinasi: **{len(kombinasi)}**")

with st.expander("🔍 Lihat Semua Kombinasi"):
    for i, (k, c) in enumerate(kombinasi, 1):
        st.write(f"{i}. {kaos_imgs[k]} + {celana_imgs[c]}")

st.markdown("### 3. Bandingkan dengan Rumus Matematika")
rumus = len(kaos_list) * len(celana_list)
st.info(f"Rumus: 4 × 3 = **{rumus}**")
if len(kombinasi) == rumus:
    st.success("✅ Visual cocok dengan rumus!")
else:
    st.warning("⚠️ Coba pilih semua opsi kaos & celana.")