# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1eSLcF8EbfI9QnTa6CziKeJBt8hVp1L
"""

import streamlit as st
from itertools import product
from PIL import Image

st.set_page_config(page_title="Kombinasi Baju", layout="centered")

st.title("👕👗 Kombinasi Baju Laki-Laki dan Perempuan")

st.markdown("### Pilih baju laki-laki:")
baju_laki = {
    "L1": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Tshirt.svg/240px-Tshirt.svg.png",
    "L2": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Tshirt_red.svg/240px-Tshirt_red.svg.png",
    "L3": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Tshirt_blue.svg/240px-Tshirt_blue.svg.png"
}

laki_selected = st.multiselect("Pilih baju laki-laki", list(baju_laki.keys()), default=["L1", "L2"])

cols = st.columns(len(laki_selected))
for i, item in enumerate(laki_selected):
    with cols[i]:
        st.image(baju_laki[item], caption=item, width=100)

st.markdown("### Pilih baju perempuan:")
baju_perempuan = {
    "P1": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Dress_icon.png/240px-Dress_icon.png",
    "P2": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Sundress_icon.png/240px-Sundress_icon.png",
    "P3": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Red_dress_icon.png/240px-Red_dress_icon.png"
}

perempuan_selected = st.multiselect("Pilih baju perempuan", list(baju_perempuan.keys()), default=["P1", "P2"])

cols2 = st.columns(len(perempuan_selected))
for i, item in enumerate(perempuan_selected):
    with cols2[i]:
        st.image(baju_perempuan[item], caption=item, width=100)

# Hitung kombinasi
if st.button("🔍 Lihat Kombinasi"):
    if not laki_selected or not perempuan_selected:
        st.warning("Pilih minimal satu baju laki-laki dan satu baju perempuan.")
    else:
        st.success(f"Jumlah kombinasi: {len(laki_selected) * len(perempuan_selected)}")
        st.markdown("### 👕 Kombinasi Visual:")
        for l, p in product(laki_selected, perempuan_selected):
            col1, col2 = st.columns(2)
            with col1:
                st.image(baju_laki[l], caption=f"Laki-laki: {l}", width=120)
            with col2:
                st.image(baju_perempuan[p], caption=f"Perempuan: {p}", width=120)
            st.markdown("---")